from django.urls import path

from . import views
from .views import check, decorator, function, get, login, post, update, delete, notice
from .views.decorator import post_required

urlpatterns = [
    path('login/', post_required(login.login_view), name='login'),
    path('register/', post_required(login.register_view), name='register'),
    path('logout/', post_required(login.logout_view), name='logout'),
    path('get/', post_required(get.get_view), name='get'),
    path('sendmsg/', post_required(function.send_msg_view), name='sendmsg'),
    path('postavatar/',
         post_required(post.post_avatar_view),
         name='postavatar'),
    path('postprogram/',
         post_required(post.post_program_view),
         name='postprogram'),
    path('postvideo/', post_required(post.post_video_view), name='postvideo'),
    path('sendmail/', post_required(function.send_mail_view), name="sendmail"),
    path('changepassword/',
         post_required(update.change_password_view),
         name='changepassword'),
    path('changepermission/',
         post_required(update.change_permission_view),
         name='changepermission'),
    path('getprograms/',
         post_required(get.get_programs_view),
         name='getprograms'),
    path('getvideos/', post_required(get.get_videolist_view),
         name='getvideos'),
    path('downloadprogram/',
         post_required(get.download_file_view),
         name='downloadprogram'),
    path('checking/', post_required(check.checking_view)),
    path('checksuccess/', post_required(check.checksuccess_view)),
    path('checkfailed/', post_required(check.checkfailed_view)),
    path('submit/', post_required(check.submit_view)),
    path('send/', post_required(check.send_view)),
    path('done/', post_required(check.done_view)),
    path('creategroup/', post_required(update.create_group_view)),
    path('getgroupprograms/', post_required(get.get_group_programs_view)),
    path('postarticle/', post_required(post.post_article_view)),
    path('getarticles/', post_required(get.get_articles_view)),
    path('appendgroup/', post_required(update.append_group_view)),
    path('checkgroup/', post_required(check.check_group_view)),
    path('getgroups/', post_required(get.get_groups_view)),
    path('deleteuser/', post_required(update.delete_user_view)),
    path('like/', post_required(update.like_view)),
    path('getpending/', post_required(get.get_pending_programs_view)),
    path('getusers/', post_required(get.get_users_view)),
    path('deletevideo/', post_required(delete.delete_video_view)),
    path('changedescription/', post_required(delete.change_description_view)),
    path('deletepost/', post_required(delete.delete_article_view)),
    path('changemobile/', post_required(update.change_mobile_view)),
    path('changeemail/', post_required(update.change_email_view)),
    path('searchvideo/', post_required(get.search_video_view)),
    path('readnotice/', post_required(notice.read_notice_view)),
    path('searchpost/', post_required(get.search_post_view)),
]
