# Generated by Django 2.2.4 on 2019-10-24 04:09

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20191023_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='text',
            field=models.FileField(default='programs/defaule.py', upload_to=login.models.upload_to_file),
        ),
    ]
