# Generated by Django 2.2.4 on 2019-10-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20191024_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='permission',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
