# Generated by Django 2.2.4 on 2019-10-30 11:44

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_userextension_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='status',
            field=models.CharField(default='POSTED', max_length=10),
        ),
        migrations.AlterField(
            model_name='program',
            name='text',
            field=models.FileField(default='programs/default.py', upload_to=login.models.upload_to_file),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='permission',
            field=models.CharField(default='USER', max_length=20),
        ),
    ]
