# Generated by Django 2.2.4 on 2019-10-31 07:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20191030_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='create_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 7, 19, 55, 650871, tzinfo=utc)),
        ),
    ]
