# Generated by Django 2.2.4 on 2019-10-31 07:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20191031_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='post_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 7, 21, 18, 745682, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='program',
            name='create_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 7, 21, 18, 745682, tzinfo=utc)),
        ),
    ]
