# Generated by Django 2.2.4 on 2019-10-31 08:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20191031_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='create_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 8, 23, 58, 993574, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='program',
            name='post_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 8, 23, 58, 993574, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('video', models.FileField(default='videos/default.mp4', upload_to=login.models.upload_to_video)),
                ('description', models.CharField(max_length=200)),
                ('create_timestamp', models.DateTimeField(default=datetime.datetime(2019, 10, 31, 8, 23, 58, 994590, tzinfo=utc))),
                ('post_timestamp', models.DateTimeField(default=datetime.datetime(2019, 10, 31, 8, 23, 58, 994590, tzinfo=utc))),
                ('stars', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='login.UserExtension')),
            ],
        ),
    ]
