# Generated by Django 2.2.4 on 2019-10-31 08:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20191031_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userextension',
            name='school',
            field=models.CharField(default='Tsinghua', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='program',
            name='create_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 8, 38, 24, 955132, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='program',
            name='post_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 8, 38, 24, 955132, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='video',
            name='create_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 8, 38, 24, 956129, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='video',
            name='post_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 8, 38, 24, 956129, tzinfo=utc)),
        ),
    ]
