# Generated by Django 2.2.4 on 2019-10-31 12:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20191031_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='create_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 12, 55, 52, 116593, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='program',
            name='post_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 12, 55, 52, 116593, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='program',
            name='status',
            field=models.CharField(default='TOCHECK', max_length=10),
        ),
        migrations.AlterField(
            model_name='video',
            name='create_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 12, 55, 52, 117590, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='video',
            name='post_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 12, 55, 52, 117590, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.CharField(default='default.mp4', max_length=100),
        ),
    ]
