# Generated by Django 2.2.4 on 2019-11-04 12:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20191031_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='create_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 12, 48, 47, 542076, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='program',
            name='post_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 12, 48, 47, 542076, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='video',
            name='create_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 12, 48, 47, 542076, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='video',
            name='post_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 12, 48, 47, 542076, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(default='', upload_to=login.models.upload_to_video),
        ),
    ]
