# Generated by Django 2.2.4 on 2019-11-05 09:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20191105_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='create_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 9, 14, 52, 803004, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='program',
            name='post_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 9, 14, 52, 803004, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='video',
            name='create_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 9, 14, 52, 803004, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='video',
            name='post_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 9, 14, 52, 803004, tzinfo=utc)),
        ),
    ]
