# Generated by Django 2.2.4 on 2019-11-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_auto_20191105_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='gstatus',
            field=models.BooleanField(default=False),
        ),
    ]
