# Generated by Django 2.2.4 on 2019-11-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_auto_20191105_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='likemans',
            field=models.ManyToManyField(related_name='likeprograms', to='login.UserExtension'),
        ),
    ]
