# Generated by Django 2.2.4 on 2019-11-07 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_program_likemans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='likemans',
        ),
        migrations.CreateModel(
            name='LikeHandle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UserExtension')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='likeusers',
            field=models.ManyToManyField(related_name='likeprograms', through='login.LikeHandle', to='login.UserExtension'),
        ),
    ]
