# Generated by Django 2.2.4 on 2019-11-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_auto_20191107_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='status',
            field=models.CharField(default='TOCHECK', max_length=20),
        ),
    ]
