# Generated by Django 2.2.4 on 2019-11-19 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_auto_20191107_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='notice', max_length=100)),
                ('text', models.CharField(default='', max_length=500)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='UNREAD', max_length=10)),
                ('fromuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publishnotices', to='login.UserExtension')),
                ('touser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='login.UserExtension')),
            ],
        ),
    ]
